controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - sliding_joint
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
